# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    types: [opened, synchronize, ready_for_review]
    paths-ignore:
      - '**/*.md'
jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
    - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # 5.0.0
    - name: run tests
      uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444 # 5.0.0
      with:
        node-version: '20.x'
    - run: yarn install
    - run: npx playwright install --with-deps chromium
    - run: CI=1 yarn test
